### ISSUE TITLE
Decoder doesn't ignore LF/CR and other characters

### ISSUE THREAD

**Issue by feelfree69** [iskolbin/lbase64#1]
LineFeeds, CarriageReturns etc. in encoded strings must be ignored. 
Currently, decoding such strings fails with an error message:
lua5.3: ./base64.lua:130: attempt to perform arithmetic on a nil value (field '?')

**Comment by iskolbin** [comment]
Added `gsub`ing to `''` on non-decodable characters. Check it out please

**Comment by feelfree69** [comment]
Yes, this works. Thanks for the quick fix!
