### ISSUE TITLE
Upload to luarocks

### ISSUE THREAD

**Issue by Yiyiyimu** [iskolbin/lbase64#2]
Hi iskolbin,

It's such a dedicated realization for base64 operation! Have you considered uploading it to luarocks? It might be easier to embedded to other softwares.

Again, thank you for your contribution!

**Comment by iskolbin** [comment]
Hi there! Thank you for using this lib. Uploaded to luarocks, you could install it with
`luarocks install base64`.

**Comment by Yiyiyimu** [comment]
Thank you for your help! Have a good day!
